apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-file-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/file-demo-shared
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-file-pvc
  namespace: file-demo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
